# Generated by Django 3.0.8 on 2020-09-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_tran_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tran',
            name='a',
        ),
    ]
